name: Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug", "SWoC26"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please provide detailed information to help us resolve it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the bug
      placeholder: Describe what's wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Frontend
        - Backend
        - Database
        - Authentication
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Browser, Device
      placeholder: "Windows 11, Chrome 120, Desktop"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, logs, or other relevant information