name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "SWoC26"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature. Please provide clear details about your proposal.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: This feature would help with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: The feature should...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Frontend
        - Backend
        - AI/ML
        - Database
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternatives?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, examples, or references